# Generated by Django 3.2.6 on 2021-11-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recieve_promotions',
            field=models.BooleanField(default=False),
        ),
    ]
