# Generated by Django 3.2.6 on 2021-10-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='billing_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
