# Generated by Django 3.2.6 on 2021-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_creditcard_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
