# Generated by Django 3.2.6 on 2021-10-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_creditcard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
