# Generated by Django 3.2.6 on 2021-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20211028_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
