# Generated by Django 3.2.6 on 2021-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_creditcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
