# Generated by Django 3.2.6 on 2021-10-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_creditcard_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
