# Generated by Django 3.2.6 on 2021-10-01 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 0, 11, 55, 92669)),
        ),
    ]
