# Generated by Django 3.2.6 on 2021-10-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20211020_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='seat_row',
        ),
    ]
