# Generated by Django 3.2.6 on 2021-10-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_show_seat_row'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'number', 'room')},
        ),
    ]
