# Generated by Django 3.2.6 on 2021-10-21 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_seat_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='show',
            name='amount',
        ),
    ]
