# Generated by Django 3.2.6 on 2021-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20211021_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='drama', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(default='Trailer not available'),
        ),
    ]
