# Generated by Django 3.2.6 on 2021-11-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20211116_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('drama', 'Drama'), ('action', 'Action'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('romance', 'Romance')], default='drama', max_length=100),
        ),
    ]
