# Generated by Django 3.2.6 on 2021-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
