# Generated by Django 3.2.6 on 2021-11-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_is_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
    ]
