# Generated by Django 3.2.6 on 2021-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_movie_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promo_code',
            field=models.CharField(default='promo1', max_length=100, unique=True),
        ),
    ]
