# Generated by Django 3.2.6 on 2021-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20211117_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
