# Generated by Django 3.2.6 on 2021-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_promotion_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='is_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
