# Generated by Django 3.2.6 on 2021-12-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_alter_promotion_is_sent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
