# Generated by Django 3.2.6 on 2021-10-21 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0008_auto_20211021_0113'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_ticket', models.IntegerField(default=1)),
                ('booking_total', models.FloatField(default=10)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_refundable', models.BooleanField(default=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='final_price',
            new_name='price',
        ),
        migrations.DeleteModel(
            name='TicketHistory',
        ),
    ]
