# Generated by Django 3.2.6 on 2021-11-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_promotion_expiration_date'),
        ('ticket', '0002_auto_20211021_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.booking'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.show'),
        ),
    ]
